version: "3.1"
#Indicamos la version de docker compose que utilizamos
#Y luego los servicios que vamos a implementar
services:
    servidorsql:
        image: mysql:latest
        container_name: sql
        ports:
            - 3307:3307
        command: --default-authentication-plugin=mysql_native_password
        environment:
            #Base de datos que utilizaremos.
            MYSQ_DATABASE: tutorias
            #Contraseña para root.
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./base_datos:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    php:
        build:
        ports:
            - 9090:80
        volumes:
            #Indicamos con quien va relacionado
            - ./pagina:/var/www/html
        links:
            #Indicamos con quien va relacionado
            - servidorsql
        networks:
            - default
        container_name: hostingphp
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        links: 
            #Indicamos con quien va relacionado
            - servidorsql:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 1234
volumes:
    persistent: