version: "3.1"
services:
    mysql_db:
        image: mysql:latest
        container_name: DB_MYSQL
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: Occidental_Escuinapa
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    pagina:
        image: php:8.0.0-apache
        build:
          context: ./Dockerfile
          dockerfile: apache_file
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
        container_name: ServidorPHP
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: Admin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
          - PMA_ARBITRARY=1            
volumes:
    persistent:
